---
apiVersion: v1
kind: Pod
metadata:
  name: zivotbot-manual
  labels:
    role: myrole
spec:
  containers:
    - name: zivotbot
      image: quay.io/cceshop/zivotbot:0.1.3
      volumeMounts:
        - name: sqlite3-storage
          mountPath: /app/db/zivotbot.db
          readOnly: false
  volumes:
    - name: sqlite3-storage
      hostPath:
        path: /opt/zivotbot/db/zivotbot.db
        type: File
  restartPolicy: OnFailure
